services:
  nginx:
    image: nginx:alpine
    ports:
      - "8182:80"
    volumes:
      - ./var_www_html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: akrez/php-fpm:8.2.0
    build:
      context: ./php8.2
      args:
        WWWGROUP: 1000
    volumes:
      - ./var_www_html:/var/www/html
